---

# Copyright 2017 David Stanek <dstanek@dstanek.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: setup MediaWiki
  hosts: all
  gather_facts: true
  remote_user: root
  vars:
  vars_files:
    - vars.yml
    - data.yml
  pre_tasks:
    - package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ software_packages }}"
    - service:
        name: "{{ item }}"
        state: started
      with_items:
        - httpd
        - mariadb
    - firewalld:
        service: http
        permanent: true
        state: enabled
      with_items:
        - http
        - https
    - blockinfile:
        dest: /etc/httpd/conf.d/mediawiki.conf
        block: |
          Alias /wiki/skins /usr/share/mediawiki/skins
          Alias /wiki /var/www/wiki
      notify:
        - restart httpd
    - mysql_db:
        name: wiki
        state: present
    - mysql_user:
        name: wiki
        password: "{{ wiki_password }}"
        priv: wiki.*:ALL
        state: present
    - template:
        src: files/LocalSettings.php.j2
        dest: /var/www/wiki/LocalSettings.php
      notify:
        - restart httpd
    - name: "install mediawiki extensions"
      unarchive:
        src: "{{ wikimedia_extensions[item] }}"
        dest: "/var/www/wiki/extensions"
        creates: "/var/www/wiki/extensions/{{ item }}"
        remote_src: yes
      with_items: "{{ wikimedia_extensions }}"
    - copy:
        src: files/cardinal.png
        dest: /var/www/wiki/images/
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
